---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: 包含多項新功能與增強功能的資訊。Cloud Volumes ONTAP 
---
= 更新功能Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
包含多項新功能與增強功能的資訊。Cloud Volumes ONTAP

最新版Cloud Manager也會提供其他功能與增強功能。請參閱 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["Cloud Manager版本資訊"^] 以取得詳細資料。



== 授權更新（2022年2月9日）

我們推出下列Cloud Volumes ONTAP 市場變化以供參考：

* Essentials套件和專業版套件現已在AWS和Google Cloud市場推出。
+
這些隨容量付費方法可讓您按小時付費、或直接向雲端供應商購買年度合約。您仍可選擇直接向NetApp購買隨容量授權。

+
如果您在雲端市場中有現有的訂閱、您也會自動訂閱這些新服務項目。您可以在部署全新Cloud Volumes ONTAP 的運作環境時、選擇隨容量充電。

+
如果您是新客戶、Cloud Manager會在您建立新的工作環境時提示您訂閱。

* 透過AWS和Google Cloud市場取得的個別節點授權已過時、不再適用於新訂閱者。這包括年度合約和每小時訂閱（Explore、Standard和Premium）。
+
目前有有效訂閱的客戶仍可使用此收費方法。



link:concept-licensing.html["深入瞭Cloud Volumes ONTAP 解適用於NetApp的授權選項"]。



== 9.10.1 GA（2022年1月31日）

目前已推出《The General Availability》（GA）版Cloud Volumes ONTAP 的《The》（英文）。GA版本包含錯誤修正。

Cloud Manager會提示您升級執行下列任一版本的現有系統：9.10.1 RC1、9.10.0或9.9.1。



== 支援更多VM類型（2021年1月2日）

在Cloud Manager 3.9.14版本中、Cloud Volumes ONTAP 從9.10.1版本開始、下列Microsoft Azure VM類型現在支援下列功能：

* E4ds_v4
* E8ds_v4
* E32ds_v4
* E48ds_v4


前往 link:reference-configs-azure.html["支援的組態頁面"] 以取得更多詳細資料。



== 9.10.1 RC1（2021年11月28日）

AWS、Azure和Google Cloud現已提供版本號為9.10.1的候選版本1。Cloud Volumes ONTAP此版本包含下列新功能與增強功能。



=== Microsoft Azure的HA增強功能

* 我們縮短Cloud Volumes ONTAP 了在Microsoft Azure上執行的不計畫性的更新容錯移轉時間。
* 現在支援NFSv4。


若要讓Cloud Volumes ONTAP 這些增強功能適用於整個過程、您必須啟用Azure訂閱的功能。具備「擁有者」權限的Azure使用者可從Azure CLI啟用此功能：

[source, azurecli]
----
az account set -s AZURE_SUBSCRIPTION_NAME_OR_ID
az feature register --name EnableHighAvailabilityMode --namespace Microsoft.Network
az provider register -n Microsoft.Network
----
Cloud Manager會在Cloud Volumes ONTAP 必要行動訊息中、針對需要在Azure訂閱中啟用功能的應用程式、提示您提供這些詳細資料。

請注意下列事項：

* 高可用度Cloud Volumes ONTAP 的不存在任何問題。此Azure功能可搭配ONTAP 使用、以減少因非計畫性容錯移轉事件而導致NFS傳輸協定的應用程式停機時間。
* 啟用此功能對Cloud Volumes ONTAP 功能不中斷運作、不中斷對功能的支援。
* 在您的Azure訂閱中啟用此功能、不會對其他VM造成問題。




=== 安全性增強功能

我們強化ONTAP 了建立影像的安全性、Cloud Volumes ONTAP 以及加強了功能完善的可靠性。



=== 支援Keystone Flex訂閱

在Cloud Manager 3.9.13版本中、您現在可以搭配Cloud Volumes ONTAP 使用Keystone Flex訂閱搭配各種HA配對。Keystone Flex訂閱是一種隨需付費的訂閱型服務、可為偏好使用營運成本消費模式的使用者、提供無縫的混合雲體驗、以預先支付資本支出或租賃。

Keystone Flex訂閱支援所有可Cloud Volumes ONTAP 從Cloud Manager部署的全新版本的功能。



=== 加密金鑰管理

發行版《支援升級》的《支援升級》、可讓您使用Azure Key Vault（AKV）或Google Cloud Key Management Service來保護各項加密金鑰。ONTAP ONTAP

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-security.html["深入瞭Cloud Volumes ONTAP 解支援for NetApp的加密技術"^]。



== Cloud Manager Connector的必要版本

Cloud Manager Connector必須執行3.9.13版或更新版本、才能部署新Cloud Volumes ONTAP 的版本號、並將現有系統升級至9.10.1版。


TIP: 連接器的自動升級預設為啟用、因此您應該執行最新版本。



== 升級附註

* 必須從 Cloud Manager 完成升級。 Cloud Volumes ONTAP您不應 Cloud Volumes ONTAP 使用 System Manager 或 CLI 來升級功能。這樣做可能會影響系統穩定性。
* 您可以從Cloud Volumes ONTAP 9.10.0版本和9.9.1版本升級至版本的版本。Cloud Manager會提示您將合格Cloud Volumes ONTAP 的更新版升級至9.10.1版。
+
http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html["瞭解如何在Cloud Manager通知您的情況下進行升級"^]。

* 單一節點系統的升級可讓系統離線長達25分鐘、在此期間I/O會中斷。
* 升級 HA 配對不中斷營運、而且 I/O 不中斷。在此不中斷營運的升級程序中、會同時升級每個節點、以繼續為用戶端提供 I/O 服務。




=== c4、m4和r4執行個體類型

從9.8版開始、新Cloud Volumes ONTAP 版的更新版不支援C4、M4和R4執行個體類型。如果您現有Cloud Volumes ONTAP 的某個執行於c4、m4或r4執行個體類型上的版本、您仍可升級至此版本。

建議變更為c5、m5或R5執行個體系列中的執行個體類型。



=== DS3_v2

從9.9.1版開始、DS3_v2 VM類型不再支援新的和現有Cloud Volumes ONTAP 的版本。如果此VM類型上有執行的現有系統、則在升級至9.10.1之前、必須先變更VM類型。
